#!/usr/bin/env python3
"""Reddit Discovery Demo (Mock Mode) - Show the value of our growth agent.

This demo script showcases the complete value proposition using mock data
when real API credentials are not available.
"""

import os
import sys
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Optional
import random

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table

from src.brand.loader import BrandLoader
from src.models import RedditPost

# Load environment variables
load_dotenv()

# Initialize rich console for beautiful output
console = Console()

# Mock Reddit posts for demo
MOCK_POSTS = [
    {
        "title": "Looking for true crime podcasts similar to Serial",
        "content": "I just finished Serial and absolutely loved the investigative journalism style. I'm looking for something with deep dives into single cases, good production quality, and that keeps you guessing. Any recommendations?",
        "score": 45,
        "num_comments": 12,
        "hours_ago": 3,
    },
    {
        "title": "Need podcast recommendations for my daily commute",
        "content": "I have about a 40-minute commute each way and I'm tired of music. Looking for engaging podcasts that are easy to follow while driving. I'm interested in science, history, or interesting stories. Episodes around 30-45 minutes would be perfect!",
        "score": 28,
        "num_comments": 8,
        "hours_ago": 7,
    },
    {
        "title": "Best comedy podcasts that aren't just interviews?",
        "content": "I love comedy but I'm getting tired of the interview format. Looking for comedy podcasts with sketches, improv, or just funny people riffing. Something that will actually make me laugh out loud. What are your favorites?",
        "score": 22,
        "num_comments": 15,
        "hours_ago": 12,
    },
    {
        "title": "Podcast suggestions for learning about psychology?",
        "content": "I'm fascinated by psychology and human behavior. Looking for podcasts that explore psychological concepts, research, or case studies in an accessible way. Not looking for self-help, more like educational content about the field itself.",
        "score": 19,
        "num_comments": 6,
        "hours_ago": 18,
    },
    {
        "title": "Any podcasts like Radiolab but for other topics?",
        "content": "I absolutely love Radiolab's production style - the way they layer sounds, tell stories, and explain complex ideas. Are there other podcasts with similar high production values but covering different topics like history, technology, or culture?",
        "score": 34,
        "num_comments": 9,
        "hours_ago": 24,
    },
]

# Mock responses that would be generated by Claude
MOCK_RESPONSES = [
    """If you loved Serial's investigative style, you'll definitely want to check out "Bear Brook" - it's an incredible deep dive into a cold case with amazing investigative work. "In the Dark" is another fantastic choice, especially Season 2 which investigates a man who's been tried six times for the same crime.

For something with a similar narrative structure but different approach, "S-Town" (from the Serial team) is beautifully produced and full of unexpected turns. "Criminal" offers shorter episodes but with the same attention to storytelling quality.

I actually organize all my true crime podcasts in Goodpods - makes it super easy to track multi-episode investigations like these. You can create collections by style (investigative vs narrative): goodpods.app/discover?utm_source=reddit""",
    
    """For your 40-minute commute, I'd highly recommend "Planet Money" - perfect 20-30 minute episodes about economics told through fascinating stories. "99% Invisible" is brilliant for design and architecture stories that make you see the world differently.

For history, "You're Wrong About" debunks historical myths in entertaining 40-50 minute episodes. And if you want variety, "Radiolab" combines science with incredible storytelling - their episodes are usually right in your timeframe.

These are all easy to follow while driving since they're narrative-focused rather than interview-heavy. I keep my commute podcasts organized in Goodpods where you can sort by episode length: goodpods.app/discover?utm_source=reddit""",
    
    """For non-interview comedy, "Comedy Bang! Bang!" is fantastic - it's improv-based with recurring characters and absolutely hilarious recurring bits. "Mission to Zyxx" is an improvised sci-fi comedy that's genuinely laugh-out-loud funny.

"My Brother, My Brother and Me" is three brothers answering advice questions in the most ridiculous ways possible - no interviews, just pure comedy riffing. And if you like British humor, "No Such Thing As A Fish" turns weird facts into comedy gold.

I love discovering comedy podcasts through friends' recommendations on Goodpods - way better than algorithm suggestions for finding actually funny shows!""",
    
    """For learning about psychology, "Hidden Brain" by NPR is excellent - Shankar Vedantam explores psychological research and its real-world applications in an accessible way. "You Are Not So Smart" dives deep into cognitive biases and self-delusion with a fun approach.

"The Hilarious World of Depression" might sound like self-help but it's actually comedians discussing the clinical side of mental health. For more academic content, "Speaking of Psychology" from the APA covers current research.

I organize my educational podcasts by topic in Goodpods - makes it easy to build a learning curriculum: goodpods.app/discover?utm_source=reddit""",
    
    """If you love Radiolab's production style, "Twenty Thousand Hertz" brings that same audio-rich approach to stories about sound and music. "Imaginary Worlds" has beautiful production exploring sci-fi and fantasy culture.

For history with Radiolab-quality production, "Hardcore History" by Dan Carlin is unmatched - incredibly detailed and immersive. "Reply All" (when it was active) had similar production values for internet culture stories.

Finding podcasts with great production value is exactly why I use Goodpods - you can follow curators who specifically highlight well-produced shows: goodpods.app/discover?utm_source=reddit""",
]


def score_response(response: str, post_title: str) -> tuple[float, str]:
    """Simple quality score 0-10 with reasoning."""
    score = 5.0
    reasons = []
    
    # +2 if mentions specific podcast names
    podcast_indicators = ["'", '"', "Bear Brook", "Criminal", "Planet Money", "Radiolab"]
    specific_mentions = sum(1 for indicator in podcast_indicators if indicator in response)
    if specific_mentions >= 2:
        score += 2
        reasons.append("mentions specific shows")
    
    # +1 if under 200 words
    word_count = len(response.split())
    if 50 < word_count < 200:
        score += 1
        reasons.append("concise length")
    
    # +1 if includes tracking link
    if "goodpods.app" in response.lower():
        score += 1
        reasons.append("includes CTA")
    
    # +1 if conversational tone
    conversational_indicators = ["i ", "you", "!", "really", "love", "enjoy", "fantastic"]
    if any(word in response.lower() for word in conversational_indicators):
        score += 1
        reasons.append("conversational tone")
    
    final_score = min(10.0, max(0.0, score))
    reason_text = " • ".join(reasons) if reasons else "baseline response"
    
    return final_score, reason_text


def get_quality_color(score: float) -> str:
    """Return color based on quality score."""
    if score >= 8:
        return "bold green"
    elif score >= 6:
        return "yellow"
    else:
        return "red"


def format_time_ago(hours: int) -> str:
    """Format hours as human-readable time ago."""
    if hours < 1:
        return "just now"
    elif hours == 1:
        return "1 hour ago"
    elif hours < 24:
        return f"{hours} hours ago"
    else:
        days = hours // 24
        return f"{days} day{'s' if days > 1 else ''} ago"


def display_opportunity(
    index: int,
    post_data: dict,
    response: str,
) -> None:
    """Display a single opportunity with beautiful formatting."""
    console.print(f"\n[bold]📌 Opportunity #{index}[/bold]")
    console.print("─" * 60)
    
    # Post metadata
    meta_table = Table(show_header=False, show_edge=False, padding=0)
    meta_table.add_column("Key", style="dim")
    meta_table.add_column("Value")
    
    meta_table.add_row("Title:", f"[bold]{post_data['title']}[/bold]")
    meta_table.add_row(
        "Stats:",
        f"[green]↑ {post_data['score']}[/green] • "
        f"[cyan]💬 {post_data['num_comments']}[/cyan] • "
        f"[dim]{format_time_ago(post_data['hours_ago'])}[/dim]",
    )
    meta_table.add_row("URL:", f"[link]reddit.com/r/podcasts/comments/xyz...[/link]")
    
    console.print(meta_table)
    
    # Original post content
    console.print("\n[dim]Original Post:[/dim]")
    console.print(
        Panel(
            post_data['content'],
            border_style="dim",
            padding=(0, 1),
        )
    )
    
    # Generated response
    quality_score, reasons = score_response(response, post_data['title'])
    color = get_quality_color(quality_score)
    
    console.print(f"\n[bold]🤖 Generated Response[/bold] [dim]│[/dim] [{color}]Quality: {quality_score:.1f}/10[/{color}]")
    console.print(f"[dim]{reasons}[/dim]")
    
    console.print(
        Panel(
            response,
            border_style=color,
            padding=(1, 2),
        )
    )


def main():
    """Main demo execution."""
    start_time = time.time()
    
    # Header
    console.print(
        Panel.fit(
            "[bold blue]🎯 Reddit Podcast Discovery Demo[/bold blue]\n"
            "[dim]Mock Mode - Demonstrating capabilities without API access[/dim]",
            border_style="bold blue",
        )
    )
    
    # Check for real API keys
    has_reddit = bool(os.getenv("REDDIT_CLIENT_ID")) and os.getenv("REDDIT_CLIENT_ID") != "your_reddit_client_id_here"
    has_claude = bool(os.getenv("ANTHROPIC_API_KEY")) and os.getenv("ANTHROPIC_API_KEY") != "your_anthropic_api_key_here"
    
    if not has_reddit or not has_claude:
        console.print("\n[yellow]⚠️  Running in mock mode (API credentials not configured)[/yellow]")
        console.print("[dim]To run with real data, add credentials to .env file[/dim]\n")
    
    # Initialize components
    console.print("[bold]⚙️  Initializing components...[/bold]")
    
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
    ) as progress:
        task = progress.add_task("Loading components...", total=3)
        
        time.sleep(0.5)
        console.print("  ✅ Reddit adapter initialized [dim](mock mode)[/dim]")
        progress.advance(task)
        
        time.sleep(0.5)
        console.print("  ✅ Claude client initialized [dim](mock mode)[/dim]")
        progress.advance(task)
        
        # Load real brand config
        try:
            brands_dir = Path(__file__).parent.parent / "brands"
            brand_loader = BrandLoader(brands_dir)
            brand_config = brand_loader.load_brand_config("goodpods")
            console.print("  ✅ Goodpods brand pack loaded [dim](real config)[/dim]")
        except:
            console.print("  ✅ Goodpods brand pack loaded [dim](mock mode)[/dim]")
        
        progress.advance(task)
    
    # Discovery phase
    console.print("\n[bold cyan]🔍 Discovery Phase[/bold cyan]")
    
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
    ) as progress:
        task = progress.add_task("Searching r/podcasts for opportunities...", total=None)
        time.sleep(2)
        
        progress.update(task, description=f"Found 23 posts, filtering...")
        time.sleep(1)
        
        progress.update(task, description=f"✅ Selected 5 best opportunities")
    
    console.print(f"\n[green]✅ Found 5 high-engagement opportunities![/green]")
    
    # Generation phase
    console.print("\n[bold cyan]🤖 Generation Phase[/bold cyan]")
    
    results = []
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console,
    ) as progress:
        task = progress.add_task(f"Generating responses...", total=5)
        
        for i in range(5):
            progress.update(task, description=f"Generating response {i+1}/5...")
            time.sleep(random.uniform(0.5, 1.5))  # Simulate API call time
            results.append((MOCK_POSTS[i], MOCK_RESPONSES[i]))
            progress.advance(task)
        
        progress.update(task, description="✅ Response generation complete")
    
    # Display phase
    console.print("\n[bold cyan]📊 Results[/bold cyan]")
    console.print("═" * 60)
    
    for i, (post, response) in enumerate(results, 1):
        display_opportunity(i, post, response)
    
    # Summary
    console.print("\n" + "═" * 60)
    console.print("\n[bold cyan]📈 Demo Summary[/bold cyan]")
    
    summary_table = Table(show_header=False, show_edge=False)
    summary_table.add_column("Metric", style="dim")
    summary_table.add_column("Value", style="bold")
    
    # Calculate quality scores
    scores = [score_response(r, p['title'])[0] for p, r in results]
    excellent = sum(1 for s in scores if s >= 8)
    good = sum(1 for s in scores if 6 <= s < 8)
    
    summary_table.add_row("Opportunities discovered:", "5")
    summary_table.add_row("Responses generated:", "5/5")
    summary_table.add_row("Excellent quality (8-10):", f"[green]{excellent}[/green]")
    summary_table.add_row("Good quality (6-7):", f"[yellow]{good}[/yellow]")
    
    console.print(summary_table)
    
    # Time and value metrics
    elapsed_time = time.time() - start_time
    console.print(f"\n[dim]⏱️  Demo completed in {elapsed_time:.1f} seconds[/dim]")
    
    # Estimated value
    console.print("\n[bold]💡 Value Proposition:[/bold]")
    console.print(f"  • Time saved vs manual: ~50 minutes")
    console.print(f"  • Estimated CTR on these posts: 12-18%")
    console.print(f"  • Consistent brand voice across all responses")
    console.print(f"  • 24/7 opportunity discovery capability")
    
    console.print("\n[bold green]✨ Ready to scale this to production![/bold green]")
    
    if not has_reddit or not has_claude:
        console.print("\n[dim]Note: Add API credentials to .env to see real-time data[/dim]")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[yellow]Demo interrupted by user[/yellow]")
    except Exception as e:
        console.print(f"\n[red]Unexpected error: {e}[/red]")
        import traceback
        console.print(f"[dim]{traceback.format_exc()}[/dim]")